<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<NuGetAudit>false</NuGetAudit>
	</PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Responses\**" />
    <EmbeddedResource Remove="Responses\**" />
    <None Remove="Responses\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
