// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(NetEquusDbContext))]
    [Migration("20260815113606_Perf")]
    partial class Perf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Models.Breeds.Breed", b =>
                {
                    b.Property<Guid>("BreedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BreedAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisciplineAffinity")
                        .HasColumnType("float");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int>("MinHeight")
                        .HasColumnType("int");

                    b.HasKey("BreedID");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Domain.Entities.Models.Breeds.BreedGenerationStats", b =>
                {
                    b.Property<Guid>("BreedGenerationStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BreedGenerationStatsId");

                    b.HasIndex("BreedId");

                    b.ToTable("BreedGenerationStats");
                });

            modelBuilder.Entity("Domain.Entities.Models.Breeds.BreedMinMaxStat", b =>
                {
                    b.Property<Guid>("BreedMinMaxStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attribute")
                        .HasColumnType("int");

                    b.Property<Guid>("BreedGenerationStatsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Max")
                        .HasColumnType("float");

                    b.Property<double>("Min")
                        .HasColumnType("float");

                    b.HasKey("BreedMinMaxStatId");

                    b.HasIndex("BreedGenerationStatsId");

                    b.ToTable("BreedMinMaxStats");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EquineEstate", b =>
                {
                    b.Property<Guid>("EstateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("EstateDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorseCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsSytemEstate")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEstateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstateId");

                    b.ToTable("EquineEstates");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EstateOwnership", b =>
                {
                    b.Property<int>("OwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnershipId"));

                    b.Property<Guid>("EstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimaryOwner")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OwnershipId");

                    b.HasIndex("EstateId");

                    b.HasIndex("UserId");

                    b.ToTable("EstateOwnerships");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Foaling", b =>
                {
                    b.Property<Guid>("FoalingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BirthTime")
                        .HasColumnType("int");

                    b.Property<Guid>("BreederId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateBred")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EquineEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("FoalingId");

                    b.HasIndex("BreederId");

                    b.HasIndex("DamId");

                    b.HasIndex("EquineEstateId");

                    b.HasIndex("FoalId")
                        .IsUnique()
                        .HasFilter("[FoalId] IS NOT NULL");

                    b.HasIndex("SireId");

                    b.ToTable("Foalings");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horse", b =>
                {
                    b.Property<Guid>("GuidHorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AgingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BreedingCoolDown")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CompetitionCoolDown")
                        .HasColumnType("date");

                    b.Property<decimal>("EquinsValue")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("HorseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFoal")
                        .HasColumnType("bit");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("GuidHorseId");

                    b.HasIndex("BreedId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horsestats.ConfPerfTempAttributes", b =>
                {
                    b.Property<Guid>("CPTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuidHorseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Trainability")
                        .HasColumnType("float");

                    b.HasKey("CPTId");

                    b.HasIndex("ConfId");

                    b.HasIndex("GuidHorseId")
                        .IsUnique();

                    b.HasIndex("PerfId");

                    b.ToTable("ConfPerfTempAttributes");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horsestats.ConformationAttributes", b =>
                {
                    b.Property<Guid>("ConfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BackAndLoin")
                        .HasColumnType("float");

                    b.Property<double>("BackAndTopline")
                        .HasColumnType("float");

                    b.Property<double>("ChestAndBarrel")
                        .HasColumnType("float");

                    b.Property<double>("Head")
                        .HasColumnType("float");

                    b.Property<double>("Hindquarters")
                        .HasColumnType("float");

                    b.Property<double>("Legs")
                        .HasColumnType("float");

                    b.Property<double>("Neck")
                        .HasColumnType("float");

                    b.Property<double>("Pasterns")
                        .HasColumnType("float");

                    b.Property<double>("Shoulders")
                        .HasColumnType("float");

                    b.HasKey("ConfId");

                    b.ToTable("ConformationAttributes");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horsestats.PerformanceAttributes", b =>
                {
                    b.Property<Guid>("PerfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Agility")
                        .HasColumnType("float");

                    b.Property<double>("Endurance")
                        .HasColumnType("float");

                    b.Property<double>("Gaits")
                        .HasColumnType("float");

                    b.Property<double>("Scope")
                        .HasColumnType("float");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<double>("Stride")
                        .HasColumnType("float");

                    b.Property<double>("Trainability")
                        .HasColumnType("float");

                    b.HasKey("PerfId");

                    b.ToTable("PerformanceAttributes");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseBoarding", b =>
                {
                    b.Property<Guid>("HorseBoardingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardingEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HorseGuidId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HorseBoardingId");

                    b.HasIndex("BoardingEstateId");

                    b.HasIndex("HorseGuidId");

                    b.ToTable("HorseBoardings");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseOwnership", b =>
                {
                    b.Property<Guid>("HorseOwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HorseGuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HorseOwnershipId");

                    b.HasIndex("HorseGuidId");

                    b.HasIndex("UserId");

                    b.ToTable("HorseOwnerships");
                });

            modelBuilder.Entity("Domain.Entities.Models.Sales.HorseSaleBase", b =>
                {
                    b.Property<Guid>("HorseSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfSale")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<Guid>("HorseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HorseSaleId");

                    b.HasIndex("HorseId");

                    b.HasIndex("SellerEstateId");

                    b.HasIndex("SellerUserId");

                    b.ToTable("HorseSaleBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("HorseSaleBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.HorseArtist", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("SubmissionAccepted")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionsAwaiting")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("HorseArtists");
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNpc")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeEnum")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Models.Sales.HorseTraderSale", b =>
                {
                    b.HasBaseType("Domain.Entities.Models.Sales.HorseSaleBase");

                    b.Property<Guid>("BuyerEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SalesPrice")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasIndex("BuyerEstateId");

                    b.HasIndex("BuyerUserId");

                    b.HasDiscriminator().HasValue("HorseTraderSale");
                });

            modelBuilder.Entity("Domain.Entities.Models.Breeds.BreedGenerationStats", b =>
                {
                    b.HasOne("Domain.Entities.Models.Breeds.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");
                });

            modelBuilder.Entity("Domain.Entities.Models.Breeds.BreedMinMaxStat", b =>
                {
                    b.HasOne("Domain.Entities.Models.Breeds.BreedGenerationStats", "BreedStats")
                        .WithMany("GenerationStats")
                        .HasForeignKey("BreedGenerationStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreedStats");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EstateOwnership", b =>
                {
                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "Estate")
                        .WithMany("EstateOwners")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Foaling", b =>
                {
                    b.HasOne("Domain.Entities.Models.Users.User", "Breeder")
                        .WithMany()
                        .HasForeignKey("BreederId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Dam")
                        .WithMany("FoalingDams")
                        .HasForeignKey("DamId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "FoalingEstate")
                        .WithMany()
                        .HasForeignKey("EquineEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Foal")
                        .WithOne("OffspringRecord")
                        .HasForeignKey("Domain.Entities.Models.Horses.Foaling", "FoalId");

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Sire")
                        .WithMany("FoalingSires")
                        .HasForeignKey("SireId")
                        .IsRequired();

                    b.Navigation("Breeder");

                    b.Navigation("Dam");

                    b.Navigation("Foal");

                    b.Navigation("FoalingEstate");

                    b.Navigation("Sire");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horse", b =>
                {
                    b.HasOne("Domain.Entities.Models.Breeds.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horsestats.ConfPerfTempAttributes", b =>
                {
                    b.HasOne("Domain.Entities.Models.Horses.Horsestats.ConformationAttributes", "ConformationAttributes")
                        .WithMany()
                        .HasForeignKey("ConfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Horse")
                        .WithOne("ConfPerfTempAttributes")
                        .HasForeignKey("Domain.Entities.Models.Horses.Horsestats.ConfPerfTempAttributes", "GuidHorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horsestats.PerformanceAttributes", "PerformanceAttributes")
                        .WithMany()
                        .HasForeignKey("PerfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConformationAttributes");

                    b.Navigation("Horse");

                    b.Navigation("PerformanceAttributes");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseBoarding", b =>
                {
                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "BoardingEstate")
                        .WithMany()
                        .HasForeignKey("BoardingEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseGuidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardingEstate");

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseOwnership", b =>
                {
                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseGuidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Models.Sales.HorseSaleBase", b =>
                {
                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "SellerEstate")
                        .WithMany()
                        .HasForeignKey("SellerEstateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Users.User", "SellerUser")
                        .WithMany()
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("SellerEstate");

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.HorseArtist", b =>
                {
                    b.HasOne("Domain.Entities.Models.Users.User", "User")
                        .WithOne("HorseArtist")
                        .HasForeignKey("Domain.Entities.Models.Users.HorseArtist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Models.Sales.HorseTraderSale", b =>
                {
                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "BuyerEstate")
                        .WithMany()
                        .HasForeignKey("BuyerEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Users.User", "BuyerUser")
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyerEstate");

                    b.Navigation("BuyerUser");
                });

            modelBuilder.Entity("Domain.Entities.Models.Breeds.BreedGenerationStats", b =>
                {
                    b.Navigation("GenerationStats");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EquineEstate", b =>
                {
                    b.Navigation("EstateOwners");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horse", b =>
                {
                    b.Navigation("ConfPerfTempAttributes")
                        .IsRequired();

                    b.Navigation("FoalingDams");

                    b.Navigation("FoalingSires");

                    b.Navigation("OffspringRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.User", b =>
                {
                    b.Navigation("HorseArtist")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
