// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(NetEquusDbContext))]
    [Migration("20260518072531_BoardingFixed")]
    partial class BoardingFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Models.Breeds.Breed", b =>
                {
                    b.Property<Guid>("BreedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BreedAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int>("MinHeight")
                        .HasColumnType("int");

                    b.HasKey("BreedID");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EquineEstate", b =>
                {
                    b.Property<Guid>("EstateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int");

                    b.Property<string>("EstateDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorseCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsSytemEstate")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEstateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstateId");

                    b.ToTable("EquineEstates");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EstateOwnership", b =>
                {
                    b.Property<int>("OwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnershipId"));

                    b.Property<Guid>("EstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimaryOwner")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OwnershipId");

                    b.HasIndex("EstateId");

                    b.HasIndex("UserId");

                    b.ToTable("EstateOwnerships");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Foaling", b =>
                {
                    b.Property<Guid>("FoalingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BreederId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquineEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FoalingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FoalingId");

                    b.HasIndex("DamId");

                    b.HasIndex("EquineEstateId");

                    b.HasIndex("FoalId")
                        .IsUnique();

                    b.HasIndex("SireId");

                    b.HasIndex("User");

                    b.ToTable("Foalings");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horse", b =>
                {
                    b.Property<Guid>("GuidHorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("AgingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("HorseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFoal")
                        .HasColumnType("bit");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("GuidHorseId");

                    b.HasIndex("BreedId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseBoarding", b =>
                {
                    b.Property<Guid>("HorseBoardingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardingEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HorseGuidId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HorseBoardingId");

                    b.HasIndex("BoardingEstateId");

                    b.HasIndex("HorseGuidId");

                    b.ToTable("HorseBoardings");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseOwnership", b =>
                {
                    b.Property<Guid>("HorseOwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HorseGuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HorseOwnershipId");

                    b.HasIndex("HorseGuidId");

                    b.HasIndex("UserId");

                    b.ToTable("HorseOwnerships");
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.HorseArtist", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("SubmissionAccepted")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionsAwaiting")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("HorseArtists");
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNpc")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EstateOwnership", b =>
                {
                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "Estate")
                        .WithMany("EstateOwners")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Foaling", b =>
                {
                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Dam")
                        .WithMany("FoalingDams")
                        .HasForeignKey("DamId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "FoalingEstate")
                        .WithMany()
                        .HasForeignKey("EquineEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Foal")
                        .WithOne("Foaling")
                        .HasForeignKey("Domain.Entities.Models.Horses.Foaling", "FoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Sire")
                        .WithMany("FoalingSires")
                        .HasForeignKey("SireId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Users.User", "Breeder")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breeder");

                    b.Navigation("Dam");

                    b.Navigation("Foal");

                    b.Navigation("FoalingEstate");

                    b.Navigation("Sire");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horse", b =>
                {
                    b.HasOne("Domain.Entities.Models.Breeds.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseBoarding", b =>
                {
                    b.HasOne("Domain.Entities.Models.EquineEstates.EquineEstate", "BoardingEstate")
                        .WithMany()
                        .HasForeignKey("BoardingEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseGuidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardingEstate");

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Relations.HorseOwnership", b =>
                {
                    b.HasOne("Domain.Entities.Models.Horses.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseGuidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Models.Users.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.HorseArtist", b =>
                {
                    b.HasOne("Domain.Entities.Models.Users.User", "User")
                        .WithOne("HorseArtist")
                        .HasForeignKey("Domain.Entities.Models.Users.HorseArtist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Models.EquineEstates.EquineEstate", b =>
                {
                    b.Navigation("EstateOwners");
                });

            modelBuilder.Entity("Domain.Entities.Models.Horses.Horse", b =>
                {
                    b.Navigation("Foaling")
                        .IsRequired();

                    b.Navigation("FoalingDams");

                    b.Navigation("FoalingSires");
                });

            modelBuilder.Entity("Domain.Entities.Models.Users.User", b =>
                {
                    b.Navigation("HorseArtist")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
