using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Reflection.Emit;
using System.Text;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Shared.Enums
{
    public enum HorseMareNames
    {
        Abby,
        Annabelle,
        Annie,
        Autumn,
        Bella,
        Berta,
        Betsy,
        Bossy,
        Carly,
        Caroline,
        Chloe,
        Cookie,
        Daisy,
        Dolly,
        Eleanor,
        Ellie,
        Fancy,
        Flo,
        Ginny,
        Hailey,
        Holly,
        Jade,
        Jasmine,
        Jenny,
        Juliet,
        Lady,
        Ladybird,
        Luna,
        Marigold,
        Martha,
        Mary,
        Meadow,
        Nancy,
        Nel,
        Nelly,
        Pearl,
        Penny,
        Piper,
        Princess,
        Queen,
        Queenie,
        Roseanne,
        Rosebud,
        Rosie,
        Sadie,
        Sally,
        Sassy,
        Shania,
        Shelby,
        Shirley,
        Valerie,
        Venus,
        Wanda,
        Wendy,
        Willow,
        Amber,
        Angel,
        Blossom,
        Brandy,
        Candy,
        Cinnamon,
        Clover,
        Crystal,
        Dottie,
        Fifi,
        Gigi,
        Honey,
        Ivory,
        Lacey,
        Misty,
        Olive,
        Opal,
        Peaches,
        Petal,
        Ruby,
        Sapphire,
        Snowy,
        Star,
        Tilly,
        Violet
    }
}
